services:
  ingest:
    build: .
    container_name: dueloanimalbot_ingest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./documentos:/app/documentos
      - ./jsonl_output:/app/jsonl_output
    command: node auto_ingest.cjs

  bot:
    build: .
    container_name: dueloanimalbot_bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
    command: node bot.cjs
