services:
  bot:
    build:
      context: .
      # Especifica que debe usar el Dockerfile principal
      dockerfile: Dockerfile
    container_name: dueloanimalbot_bot
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./qr:/app/qr
    restart: unless-stopped
    env_file:
      - .env
    # El comando por defecto del Dockerfile iniciará bot.cjs, así que no necesitamos especificarlo.

  ingest:
    build:
      context: .
      # --- INICIO DE LA CORRECCIÓN ---
      # Apunta al mismo Dockerfile que el bot.
      dockerfile: Dockerfile
    container_name: dueloanimalbot_ingest
    volumes:
      - ./documentos:/app/documentos
      - ./jsonl_output:/app/jsonl_output
    restart: unless-stopped
    env_file:
      - .env
    # Le decimos a este servicio que, en lugar del comando por defecto, ejecute el script de ingesta.
    command: "node auto_ingest.cjs"
    # --- FIN DE LA CORRECCIÓN ---

