services:
  redis:
    image: redis:7.2-alpine
    container_name: eva_redis
    restart: unless-stopped
    networks:
      - eva-network

  main-api:
    build:
      context: ./services/main-api
      dockerfile: Dockerfile
    container_name: eva_main_api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./services/main-api/app:/app/app
    depends_on:
      - redis
    networks:
      - eva-network

  whatsapp-gateway:
    build:
      context: ./services/whatsapp-gateway
      dockerfile: Dockerfile
    container_name: eva_whatsapp_gateway
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - whatsapp_session:/app/
    depends_on:
      - redis
    networks:
      - eva-network

  transcription-worker:
    build:
      context: ./services/transcription-worker
      dockerfile: Dockerfile
    container_name: eva_transcription_worker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./services/transcription-worker/app:/app/app
    depends_on:
      - redis
    networks:
      - eva-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: eva_frontend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - main-api
    networks:
      - eva-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: eva_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - main-api
      - frontend
    networks:
      - eva-network

volumes:
  whatsapp_session:

networks:
  eva-network:
    driver: bridge
