services:
  dueloanimalbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dueloanimalbot
    volumes:
      - ./documentos:/app/documentos
      - ./jsonl_output:/app/jsonl_output
    env_file:
      - .env
    restart: unless-stopped
    command: node auto_ingest.cjs
