services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crezgo_backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000" # For local development and debugging

  whatsapp:
    build:
      context: ./whatsapp
      dockerfile: Dockerfile
    container_name: crezgo_whatsapp
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount a volume to persist the WhatsApp session data
      - whatsapp_session:/app/.wwebjs_auth
    depends_on:
      - nginx

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: crezgo_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  whatsapp_session:
