groups:
- name: HostAndContainerAlerts
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instancia {{ $labels.instance }} caída"
      description: "El servicio {{ $labels.job }} en la instancia {{ $labels.instance }} ha estado caído por más de 1 minuto."

  - alert: HighCpuUsage
    # This alert triggers if the CPU usage of any container is above 80% for 5 minutes.
    # It uses metrics from cAdvisor, which is already in the stack.
    # The expression calculates the non-idle CPU time as a percentage.
    expr: (100 * (1 - avg by (container_label_com_docker_compose_service) (rate(node_cpu_seconds_total{mode="idle"}[2m])))) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Uso de CPU elevado en el contenedor {{ $labels.container_label_com_docker_compose_service }}"
      description: "El uso de CPU para el servicio {{ $labels.container_label_com_docker_compose_service }} ha superado el 80% durante los últimos 5 minutos."
