global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "main-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["main-api:8000"]

  - job_name: "whatsapp-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["whatsapp-gateway:9100"]
