# Top-level configuration
name = "eva-workers"
main = "transcription-worker/src/index.ts" # Default entrypoint, can be overridden per-worker
compatibility_date = "2024-05-01"

# Environment configuration for all workers
[vars]
# These secrets are placeholders and must be set via `wrangler secret put`
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY
# R2_BUCKET_NAME
# R2_ACCOUNT_ID
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY
# GOOGLE_APPLICATION_CREDENTIALS_JSON

# Definition for the Transcription Worker
[[workers]]
name = "transcription-worker"
main = "transcription-worker/src/index.ts"
compatibility_date = "2024-05-01"
# Bind this worker to consume messages from a Cloudflare Queue
[[workers.queues.consumers]]
queue = "eva-transcription-queue" # This name should match the queue created in Cloudflare
max_batch_size = 5
max_wait_ms = 1000

# Definition for the Embedding Worker
[[workers]]
name = "embedding-worker"
main = "embedding-worker/src/index.ts"
compatibility_date = "2024-05-01"
# Bind this worker to consume messages from a different queue
[[workers.queues.consumers]]
queue = "eva-embedding-queue" # This name should match the queue created in Cloudflare
max_batch_size = 5
max_wait_ms = 1000
