# .github/workflows/deploy.yml
name: Test, Build and Deploy EVA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_scan:
    name: Test & Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build environment for testing
        run: docker-compose -f docker-compose.prod.yml up --build -d

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services to initialize..."
          sleep 30 # Give services ample time to start and run healthchecks
          docker-compose -f docker-compose.prod.yml ps

      - name: Run Backend Tests
        run: docker-compose -f docker-compose.prod.yml exec -T main-api pytest

      - name: Run DLQ Monitor Tests
        run: docker-compose -f docker-compose.prod.yml exec -T dlq-monitor pytest

      - name: Run Frontend Tests
        run: docker-compose -f docker-compose.prod.yml exec -T frontend npm test

      - name: Run Backend Linters
        run: |
          echo "Linting main-api..."
          docker-compose -f docker-compose.prod.yml exec -T main-api ruff check .
          echo "Linting dlq-monitor..."
          docker-compose -f docker-compose.prod.yml exec -T dlq-monitor ruff check .
          echo "Linting embedding-worker..."
          docker-compose -f docker-compose.prod.yml exec -T embedding-worker ruff check .
          echo "Linting transcription-worker..."
          docker-compose -f docker-compose.prod.yml exec -T transcription-worker ruff check .

      - name: Run Frontend Linter
        run: docker-compose -f docker-compose.prod.yml exec -T frontend npm run lint

      - name: Scan Frontend Vulnerabilities
        run: docker-compose -f docker-compose.prod.yml exec -T frontend npm audit --audit-level=high

      - name: Scan Backend Vulnerabilities
        run: |
          docker-compose -f docker-compose.prod.yml exec -T main-api pip install pip-audit
          docker-compose -f docker-compose.prod.yml exec -T main-api pip-audit -r requirements.txt

  build_and_push:
    name: Build & Push Docker Images
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test_and_scan
    runs-on: ubuntu-latest
    outputs:
      git_sha: ${{ steps.get_sha.outputs.git_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get short git SHA
        id: get_sha
        run: echo "git_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push services
        run: |
          GIT_SHA=${{ steps.get_sha.outputs.git_sha }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-main-api:$GIT_SHA -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-main-api:latest ./services/main-api
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-whatsapp-gateway:$GIT_SHA -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-whatsapp-gateway:latest ./services/whatsapp-gateway
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-transcription-worker:$GIT_SHA -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-transcription-worker:latest ./services/transcription-worker
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-embedding-worker:$GIT_SHA -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-embedding-worker:latest ./services/embedding-worker
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-dlq-monitor:$GIT_SHA -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-dlq-monitor:latest ./services/dlq-monitor
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-frontend:$GIT_SHA -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-frontend:latest ./frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-supabase-cli:$GIT_SHA -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-supabase-cli:latest ./supabase
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-backup:$GIT_SHA -t ${{ secrets.DOCKERHUB_USERNAME }}/eva-backup:latest ./cron

          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/eva-main-api
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/eva-whatsapp-gateway
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/eva-transcription-worker
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/eva-embedding-worker
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/eva-dlq-monitor
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/eva-frontend
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/eva-supabase-cli
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/eva-backup

  deploy:
    name: Deploy to Production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/eva-project # IMPORTANT: Adjust to your project path

            # Set the image tags for this deployment
            export GIT_SHA=${{ needs.build_and_push.outputs.git_sha }}
            export MAIN_API_TAG=$GIT_SHA
            export WHATSAPP_GATEWAY_TAG=$GIT_SHA
            export TRANSCRIPTION_WORKER_TAG=$GIT_SHA
            export EMBEDDING_WORKER_TAG=$GIT_SHA
            export DLQ_MONITOR_TAG=$GIT_SHA
            export FRONTEND_TAG=$GIT_SHA
            export SUPABASE_CLI_TAG=$GIT_SHA
            export BACKUP_TAG=$GIT_SHA

            echo "Creating .env file from secrets..."
            cat << EOF > .env.prod
            # This file is auto-generated by the CI/CD pipeline
            DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
            CERTBOT_EMAIL=${{ secrets.CERTBOT_EMAIL }}
            # Supabase connection details
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            SUPABASE_DB_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }}
            SUPABASE_PROJECT_ID=${{ secrets.SUPABASE_PROJECT_ID }}
            SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}
            # Public Supabase details for frontend
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            # AI Provider Keys
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            OPENAI_EMBED_MODEL=text-embedding-3-large
            # R2 Storage for media
            R2_ENDPOINT_URL=${{ secrets.R2_ENDPOINT_URL }}
            R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}
            R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}
            # Service specific secrets
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            WHATSAPP_USER_ID=${{ secrets.WHATSAPP_USER_ID }}
            GRAFANA_ADMIN_PASSWORD=${{ secrets.GRAFANA_ADMIN_PASSWORD }}
            # Backup service configuration
            BACKUP_HEALTHCHECK_URL=${{ secrets.BACKUP_HEALTHCHECK_URL }}
            R2_REMOTE_NAME=${{ secrets.R2_REMOTE_NAME }}
            R2_BUCKET_PATH=${{ secrets.R2_BUCKET_PATH }}
            # Frontend URL configuration
            FRONTEND_ORIGINS=https://\${{ secrets.DOMAIN_NAME }}
            NEXT_PUBLIC_API_URL=https://\${{ secrets.DOMAIN_NAME }}/api/v1
            EOF

            echo "Pulling latest images from Docker Hub..."
            docker-compose -f docker-compose.prod.yml pull

            echo "Running database migrations..."
            docker-compose -f docker-compose.prod.yml run --rm supabase-cli supabase db push

            echo "Restarting all services..."
            docker-compose -f docker-compose.prod.yml up -d

            echo "Cleaning up old Docker images..."
            docker image prune -af

            echo "Deployment to production successful!"
