# This is the CI/CD workflow for the EVA project.
# It automatically tests, builds, and pushes Docker images on every push to main.
name: CI - Test, Lint, and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Run tests and linters
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy .env file
        run: cp .env.example .env

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be healthy
        run: sleep 30 # Give services time to start up

      - name: Lint and Test Main API (Python)
        run: |
          docker-compose exec -T main-api ruff format .
          docker-compose exec -T main-api ruff check . --fix
          docker-compose exec -T main-api pytest

      - name: Lint and Test Transcription Worker (Python)
        run: |
          docker-compose exec -T transcription-worker ruff format .
          docker-compose exec -T transcription-worker ruff check . --fix
          docker-compose exec -T transcription-worker pytest

      - name: Lint and Test Frontend (JS/TS)
        run: |
          docker-compose exec -T frontend npm run lint
          # npm run test is not set up, so this would fail.
          # Add a test script to package.json to enable this.
          # docker-compose exec -T frontend npm run test

  # Job 2: Build and push Docker images
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: test-and-lint
    # Only run this step on direct pushes to main, not on PRs
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Nginx
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eva-nginx:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eva-frontend:latest

      - name: Build and push Main API
        uses: docker/build-push-action@v5
        with:
          context: ./services/main-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eva-main-api:latest

      - name: Build and push WhatsApp Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./services/whatsapp-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eva-whatsapp-gateway:latest

      - name: Build and push Transcription Worker
        uses: docker/build-push-action@v5
        with:
          context: ./services/transcription-worker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eva-transcription-worker:latest
